"""add icon_url to collections

Revision ID: aabd29069148
Revises: 733039959fa8
Create Date: 2025-12-15 03:00:38.526007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabd29069148'
down_revision: Union[str, None] = '733039959fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('icon_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'icon_url')
    # ### end Alembic commands ###
